# Starter pipeline

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'         #use latest Ubuntu image as the build & deploy agent

variables:
  imageName: 'form-validation-with-zod-library'
  acrName: 'tellisticcr'
  acrServiceConnection: 'Tellistic Docker Container Registry Service Connection'  # Service connection requires elevated Azure permission to create
  armServiceConnection: 'Tellistic ARM Service Connection'
stages:
  - stage: Build
    displayName: 'Build Docker Image'
    jobs:                                   #jobs to run within this stage
      - job: Build
        displayName: 'Build Docker Image Job'
        steps:                              #individual tasks to run in this job
        - task: UseNode@1                   # a task to install & use Node.js 18 version
          inputs:
            version: '18.20.7'
          displayName: 'Install Node.js'

        - script: |                             #run a script install dependencies & build the app
              npm install
              npm run build
          displayName: 'Build Next.js app'

        - task: Docker@2                         #uses Docker task v2
          inputs:
            containerRegistry: $(acrServiceConnection)         #specify acr service connection
            repository: $(imageName)                           #name of the Docker repo
            command: 'buildAndPush'                            #this command builds the docker image & pushes it to the acr
            Dockerfile: 'Dockerfile'                           #path to the dockerfile the pipeline                    
            tags: |
                latest

  - stage: Deploy   #2nd stage
    displayName: 'Deploy to Azure Container Apps'
    dependsOn: Build                               #run only after the Build stage completes
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Image ACA'
        steps:
          - task: AzureCLI@2
            inputs: 
              azureSubscription: $(armServiceConnection)     #need to use ARM sservice connection
              scriptType: 'pscore'                        #running azure cli commands against an azure subscription in a ps core script (ubuntu-latest - Linux agent)
              scriptLocation: 'inlineScript'
              inlineScript: |     
               az containerapp up \                        
               --name form-validation-app \
               --resource-group Tellistic-azure-devops-RG \
               --image $(acrName).azurecr.io/$(imageName):latest                             
               echo "Deployment to ACA completed."
            displayName: 'Deployment Complete'

#az containerapp up : command for configure, deploy and update azure container app
